tasks:
  - name: Setup and run project
    init: |
      cd front/ && npm i
      cd ../node-red/ && npm i
      cd .. && docker-compose up -d

ports:
  - port: 1880
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview